name = "Ndolo"
version = "0.1.1"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ndl"

[windows]
system_product_code = "A94CB0E2-DDDA-42C5-8B82-59AA19B9B048"
msoffice_product_code = "FA1EA1AB-C26C-4058-83C0-70C259FCA28A"
