template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "ndol1238"
__REPO__ = "lang-ndl"
__UND2C__ = "ndl"
__UNDEFINED__ = "Ndolo"
__UND__ = "ndl"
