template = "https://github.com/giellalt/template-lang-und"
rev_id = 328
template_sha = "a66ce6606ea33e46cd3439c88cafa44d4dcdde92"

[replacements]
__GLOTTOLOG_ID__ = "ndol1238"
__REPO__ = "lang-ndl"
__UND2C__ = "ndl"
__UNDEFINED__ = "Ndolo"
__UND__ = "ndl"
