template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "ndol1238"
__REPO__ = "lang-ndl"
__UND2C__ = "ndl"
__UNDEFINED__ = "Ndolo"
__UND__ = "ndl"
