[package]
name = "ndl"
human_name = "Ndolo"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.ndl]
filename = "ndl-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-ndl"
platform = "windows"
uuid = "A94CB0E2-DDDA-42C5-8B82-59AA19B9B048"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ndl"
package = "speller-ndl"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-ndl-mso"
platform = "windows"
uuid = "FA1EA1AB-C26C-4058-83C0-70C259FCA28A"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-ndl"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
